domain: datasnok.cool
hostnames:
  - mail.datasnok.cool
initialAccount:
  enabled: true
  domain: datasnok.cool
  username: mailadmin
logLevel: INFO
persistence:
  size: 20Gi
subnet: 10.1.0.0/16

ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

rspamd:
  resources:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
