domain: datasnok.cool
hostnames:
  - mail.datasnok.cool
initialAccount:
  domain: datasnok.cool
  username: mailadmin
logLevel: INFO
mail:
  authRatelimit: 100/minute;3600/hour
  messageSizeLimitInMegabytes: 200
persistence:
  size: 20Gi
  storageClass: manual
  hostPath: /var/mailu
subnet: 10.1.0.0/16

rspamd:
  resources:
    limits:
      cpu: 600m
      memory: 500Mi
    requests:
      cpu: 500m
      memory: 500Mi
